INSERT INTO question(id,text,issue_id) VALUES (1,"Who should run the new homless shelter?",1);
INSERT INTO question(id,text,issue_id) VALUES (2,"What services should a homeless provide?",1);
INSERT INTO question(id,text,issue_id) VALUES (3,"Who should pay for the the new homless shelter?",1);
INSERT INTO question(id,text,issue_id) VALUES (4,"What are the barriers to building the new homeless shelter?",1);
INSERT INTO question(id,text,issue_id) VALUES (5,"Is there a need for a new homeless shelter?",1);
INSERT INTO question(id,text,issue_id) VALUES (6,"Will fracking cause earthquakes?",2);
INSERT INTO question(id,text,issue_id) VALUES (7,"What will be done with fracking waste?",2);
INSERT INTO question(id,text,issue_id) VALUES (8,"Will fracking pollute groundwater?",2);
INSERT INTO question(id,text,issue_id) VALUES (9,"What impact will there be on wildlife?",2);
INSERT INTO question(id,text,issue_id) VALUES (10,"How will fracking affecte Yukon communities?",2);
INSERT INTO question(id,text,issue_id) VALUES (11,"Where can I use cannabis?",3);
INSERT INTO question(id,text,issue_id) VALUES (12,"Can I grow pot?",3);
INSERT INTO question(id,text,issue_id) VALUES (13,"How much pot can I have?",3);
INSERT INTO question(id,text,issue_id) VALUES (14,"Is my medical use card still valid",3);
