INSERT INTO option(id,text,question_id) VALUES (1,"YG Health and social services",1);
INSERT INTO option(id,text,question_id) VALUES (2,"Salvation Army",1);
INSERT INTO option (id,text,question_id) VALUES (3,"A new Non-profit",1);
INSERT INTO option (id,text,question_id) VALUES (4,"Beds, meals and showers",2);
INSERT INTO option (id,text,question_id) VALUES (5,"Secure storage, laundry services, food and shelter",2);
INSERT INTO option (id,text,question_id) VALUES (6,"Health and wellness services",2);
INSERT INTO option (id,text,question_id) VALUES (7,"Private and public sector",3);
INSERT INTO option (id,text,question_id) VALUES (8,"Municipal, territorial and federal funds",3);
INSERT INTO option (id,text,question_id) VALUES (9,"Non-profits and charitable organisations",3);
INSERT INTO option (id,text,question_id) VALUES (10,"Funding and a suitable building site that ",4);
INSERT INTO option (id,text,question_id) VALUES (11,"Public apathy and lack of government initiative",4);
INSERT INTO option (id,text,question_id) VALUES (12,"The issue has not hit ""crisis mode""",4);
INSERT INTO option (id,text,question_id) VALUES (13,"Yes, the current services do not meet the needs of the homeless community.",5);
INSERT INTO option (id,text,question_id) VALUES (14,"No, the current setup is just fine",5);
INSERT INTO option (id,text,question_id) VALUES (15,"Not Sure.  Let's have a charrette…",5);
INSERT INTO option (id,text,question_id) VALUES (16,"Yes, it has happened in other jurisdictions and it will happen here!",6);
INSERT INTO option (id,text,question_id) VALUES (17,"No, that’s silly…",6);
INSERT INTO option (id,text,question_id) VALUES (18,"I'm not sure, I would like to learn more about it.",6);
INSERT INTO option (id,text,question_id) VALUES (19,"It will be cleaned, reused and if disposed of, it will be done correctly",7);
INSERT INTO option (id,text,question_id) VALUES (20,"It will be dumped, and that scares me…",7);
INSERT INTO option (id,text,question_id) VALUES (21,"I hope it will not affect the environment, will it?",7);
INSERT INTO option (id,text,question_id) VALUES (22,"Only time will tell",8);
INSERT INTO option (id,text,question_id) VALUES (23,"No",8);
INSERT INTO option (id,text,question_id) VALUES (24,"Yes",8);
INSERT INTO option (id,text,question_id) VALUES (25,"None, both can co-exist",9);
INSERT INTO option (id,text,question_id) VALUES (26,"Yes, but the wildlife is adaptable",9);
INSERT INTO option (id,text,question_id) VALUES (27,"Not sure.  Let's have a charrette…",9);
INSERT INTO option (id,text,question_id) VALUES (28,"It will create local business and employment opportunities",10);
INSERT INTO option (id,text,question_id) VALUES (29,"How will fracking affecte Yukon communities?",10);
INSERT INTO option (id,text,question_id) VALUES (30,"How will fracking affecte Yukon communities?",10);
INSERT INTO option (id,text,question_id) VALUES (31,"Cannabis consumption is legal within the confines of your private residence (house and yard), unless you use your home to run a daycare or preschool. ",11);
INSERT INTO option (id,text,question_id) VALUES (32,"If you’re caught consuming in public, a law enforcement officer will either give you a warning, seize the cannabis or issue a ticket.",11);
INSERT INTO option (id,text,question_id) VALUES (33,"Landlords can prohibit smoking or vaping and growing of cannabis plants within rental properties. Tenancy agreements that include no smoking will be interpreted to include no smoking of cannabis. ",11);
INSERT INTO option (id,text,question_id) VALUES (34,"Landlords and tenants should work together to clarify rental agreements and put what’s agreed to in writing. Questions? Email: rto@gov.yk.ca.",11);
INSERT INTO option (id,text,question_id) VALUES (35,"Yukoners can grow their own cannabis for personal use. Your house – regardless of how many people live there – can grow up to 4 plants. There is no restriction on the size of plant.  Adults are responsible for keeping kids safe from plants and their products.",12);
INSERT INTO option (id,text,question_id) VALUES (36,"Your house – regardless of how many people live there – can grow up to 4 plants. There is no restriction on the size of plant.  Adults are responsible for keeping kids safe from plants and their products.",12);
INSERT INTO option (id,text,question_id) VALUES (37," Adults are responsible for keeping kids safe from plants and their products.",12);
INSERT INTO option (id,text,question_id) VALUES (38,"Adults 19 and older can purchase up to 30 grams of dried cannabis (or its equivalent) per transaction and can possess no more than this amount in public.  ",13);
INSERT INTO option (id,text,question_id) VALUES (39,"Adults 19 and older can purchase up to 50 grams of fresh cannabis; 2,100 grams of liquid (e.g., oil) product; or 30 cannabis plant seeds. ",13);
INSERT INTO option (id,text,question_id) VALUES (40,"If you possess more than 30 grams of dried cannabis (or its equivalent) in public, law enforcement officers could ticket you or you could face criminal charges.  There is no limit to how much cannabis you can keep at home.",13);
INSERT INTO option (id,text,question_id) VALUES (41,"Rules for medical cannabis come from the Government of Canada. Find out more about accessing cannabis for medical purposes.",14);
